config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
    validates :firstname, presence:true, length: { minimum:3, maximum:50 }
    validates :lastname, presence:true, length: { minimum:3, maximum:50 }
    validates :email, presence:true, length: { minimum:3, maximum:60 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController< ApplicationController
    def home
    end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
       @user = User.all 
    end
    
    def new
      @user = User.new  
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    
    def create
     @user = User.new(user_params)
    if  @user.save
        flash[:notice] = "User was successfully created"
        redirect_to user_path(@user)
    else
            render 'new'
    end
    
    end
    
    def update
        @user = User.find(params[:id])
        
        if @user.update(user_params)
            flash[:notice]="User was successfully updated"
            redirect_to user_path(@user)
            
        else
            render 'edit'
        end
        
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def destroy
         @user = User.find(params[:id])
         @user.destroy
         
         flash[:notice] = "Article was successfully deleted"
         redirect_to users_path
        
    end
    
    private
    def user_params
        params.require(:user).permit(:firstname, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evaluation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %>
<ul>
  <li><%= msg %></li>
</ul>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Ruby on Rails First Assignment: CRUD</h1>
<p>Objective:
Evaluate the knowledge on Ruby on Rails CRUD operations.</p>

<p>Go to create user: <%= link_to "Create user", users_path%>
</p>

app/views/users/edit.html.erb
<h1>Edit existing user</h1>

<% if @user.errors.any? %>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>

<% end %>

<%= form_for @user do |f|%>

<p>
    <%= f.label :"First name:" %></br>
    <%= f.text_field :firstname %>
</p>

<p>
    <%= f.label :"Last name:" %></br>
    <%= f.text_field :lastname %>
</p>

<p>
    <%= f.label :"Email:" %></br>
    <%= f.text_field :email %>
</p>

<p>
    <%= f.submit %>


<%end%>

<%= link_to "Back to user listing", users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
    
    <tr>
     <th>First Name</th>   
     <th>Last Name</th> 
     <th>Email</th> 
     </tr>
     
     
     <% @user.each do |user|%>
     <tr>
         <td><%= user.firstname%></td>
         <td><%= user.lastname%></td>
         <td><%= user.email%></td>
         <td><%= link_to 'Edit', edit_user_path(user)%></td>
         <td><%= link_to 'Show', user_path(user)%></td>
         <td><%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"}%></td>
         
     </tr>
     
    <% end %>
</table>
<p><%= link_to "Create new user", new_user_path %></p>

app/views/users/new.html.erb
<h1>Create an User</h1>
<% if @user.errors.any? %>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>

<% end %>

<%= form_for @user do |f|%>

<p>
    <%= f.label :"First name:" %></br>
    <%= f.text_field :firstname %>
</p>

<p>
    <%= f.label :"Last name:" %></br>
    <%= f.text_field :lastname %>
</p>

<p>
    <%= f.label :"Email:" %></br>
    <%= f.text_field :email %>
</p>

<p>
    <%= f.submit %>


<%end%>

<%= link_to "Back to user listing", users_path %>

app/views/users/show.html.erb
<h1>Showing selected user</h1>

<p>
    First Name: <%= @user.firstname%>
</p>
<p>
    Last  Name: <%= @user.lastname%>
</p>
<p>
    Email:      <%= @user.email%>
</p>

<%= link_to "Edit this user", edit_user_path(@user) %>
<%= link_to "Back to user listing", users_path %>